apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  labels:
    app: notification
spec:
  replicas: 1
  template:
    metadata:
      name: notification
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: vnx10/notification:latest
          ports:
            - containerPort: 80
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
          imagePullPolicy: Always
      restartPolicy: Always
  selector:
    matchLabels:
      app: notification
