apiVersion: v1
kind: Service
metadata:
  name: notification
spec:
  selector:
    app: notification
  ports:
    - name: http
      protocol: TCP
      port: 8082
      targetPort: 8082
  type: NodePort